services:
  frontend:
    build:
      dockerfile: Dockerfile.front
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      dockerfile: Dockerfile.back
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/local_database
      - RAILS_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: local_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
